geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='category_list'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='product_list'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('reports/', adminapp.ReportsListView.as_view(), name='reports'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
    path('favourite/', authapp.FavouriteListView.as_view(), name='favourite'),
    path('favourite/delete/<int:pk>/', authapp.FavouriteDeleteView.as_view(), name='favourite_delete'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp


urlpatterns = [
    path('', mainapp.main, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('order/', include('ordersapp.urls', namespace='order')),

    # path('admin/', admin.site.urls, name='admin'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models
from django.db.models import F

from mainapp.models import Product


class Report(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    quantity = models.PositiveIntegerField(default=0, verbose_name='количество покупок')

    @staticmethod
    def get_items():
        return Report.objects.filter(quantity__gt=0).order_by('quantity')

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        exclude = ('is_active',)
        # fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', min_value=0, max_value=90, initial=0, required=False)

    class Meta:
        model = ProductCategory
        exclude = ('is_active',)
        # fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('is_active',)
        # fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.db import connection
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from adminapp.models import Report
from mainapp.models import Product, ProductCategory
from authapp.models import ShopUser
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm


class AccessMixin:
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))
    else:
        user_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'update_form': user_form
    }

    return render(request, 'adminapp/user_update.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     context = {
#         'title': title,
#         'objects': users_list
#     }
#     return render(request, 'adminapp/users.html', context)


class UsersListView(AccessMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'админка/пользователи'
        return context_data


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'
    edit_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    context = {
        'title': title,
        'update_form': edit_form
    }

    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'
    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        if user.is_active:
            user.is_active = False
        else:
            user.is_active = True
        user.save()
        return HttpResponseRedirect(reverse('adminapp:user_list'))

    context = {
        'title': title,
        'user_to_delete': user
    }

    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'категории/создание'

    if request.method == 'POST':
        category_form = ProductCategoryEditForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('adminapp:category_list'))
    else:
        category_form = ProductCategoryEditForm()

    context = {
        'title': title,
        'update_form': category_form
    }

    return render(request, 'adminapp/category_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'
    categories_list = ProductCategory.objects.all()

    context = {
        'title': title,
        'objects': categories_list
    }

    return render(request, 'adminapp/categories.html', context)


class ProductCategoryUpdateView(AccessMixin, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:category_list')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return super().form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('adminapp:category_update', args=[edit_category.pk]))
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#
#     context = {
#         'title': title,
#         'update_form': edit_form
#     }
#
#     return render(request, 'adminapp/category_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'категории/удаление'
    category_obj = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        if category_obj.is_active:
            category_obj.is_active = False
        else:
            category_obj.is_active = True
        category_obj.save()
        return HttpResponseRedirect(reverse('adminapp:category_list'))

    context = {
        'title': title,
        'category_to_delete': category_obj
    }

    return render(request, 'adminapp/category_delete.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request, pk):
#     title = 'продукт/создание'
#     category = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         product_form = ProductEditForm(request.POST, request.FILES)
#         if product_form.is_valid():
#             product_form.save()
#             return HttpResponseRedirect(reverse('adminapp:product_list', args=[pk]))
#     else:
#         product_form = ProductEditForm(initial={'category': category})
#
#     context = {
#         'title': title,
#         'update_form': product_form,
#         'category': category.pk
#     }
#
#     return render(request, 'adminapp/product_update.html', context)


class ProductCreateView(AccessMixin, CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    def get_success_url(self):
        return reverse('adminapp:product_list', args=[self.kwargs['pk']])

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'продукт/создание'
        context_data['category'] = self.kwargs.get('pk')
        return context_data


# @user_passes_test(lambda u: u.is_superuser)
# def products(request, pk):
#     title = 'админка/продукты'
#     category = get_object_or_404(ProductCategory, pk=pk)
#     products_list = Product.objects.filter(category__pk=pk).order_by('name')
#
#     context = {
#         'title': title,
#         'category': category,
#         'objects': products_list
#     }
#
#     return render(request, 'adminapp/products.html', context)


class ProductsListView(AccessMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'админка/продукты'
        context_data['category'] = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))
        return context_data

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk'))


# @user_passes_test(lambda u: u.is_superuser)
# def product_read(request, pk):
#     title = 'продукт/подробнее'
#     product = get_object_or_404(Product, pk=pk)
#
#     context = {
#         'title': title,
#         'object': product
#     }
#
#     return render(request, 'adminapp/product_read.html', context)


class ProductDetailView(AccessMixin, DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'продукт/подробнее'
        context_data['category'] = self.kwargs.get('pk')
        return context_data


# @user_passes_test(lambda u: u.is_superuser)
# def product_update(request, pk):
#     title = 'продукт/редактирование'
#     edit_product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('adminapp:product_update', args=[edit_product.pk]))
#     else:
#         edit_form = ProductEditForm(instance=edit_product)
#
#     context = {
#         'title': title,
#         'update_form': edit_form,
#         'category': edit_product.category.pk
#     }
#
#     return render(request, 'adminapp/product_update.html', context)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
    <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
    </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="categories_list">
    <button class="new_category">
        <a href={% url 'adminapp:category_create' %}>
        новая категория
        </a>
    </button>

    {% for object in objects %}
    <div class="category_record
        {% if not object.is_active %}
            not_active
        {% endif %}">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">
            <button>
                <a href={% url 'adminapp:product_list' object.pk %}>
                товары категории
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:category_update' object.pk %}>
                редактировать
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:category_delete' object.pk %}>
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
                </a>
            </button>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="user_delete">
    {% if category_to_delete.is_active %}
        Уверены, что хотите удалить
    {% else %}
        Уверены, что хотите восстановить
    {% endif %}
    категорию
    {{ category_to_delete.name }}
    ?
    <form action="{% url 'adminapp:category_delete' category_to_delete.pk %}"
          method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="уверен">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:category_list' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:category_list' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="user_delete">
    {% if object.is_active %}
        Уверены, что хотите удалить
    {% else %}
        Уверены, что хотите восстановить
    {% endif %}
    продукт
    {{ object.name }}
    ?
    <form action="{% url 'adminapp:product_delete' object.pk %}"
          method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="уверен">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:product_list' object.category.pk %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} /
                     {{ object.name|title }}</strong>
    </div>
    <img src="{{ object.image|media_for_products }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'adminapp:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:product_delete' object.pk %}>
            {% if object.is_active %}
                    удалить
            {% else %}
                    восстановить
            {% endif %}
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:product_list' object.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:product_list' category %}">
      к списку продуктов
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<div class="products_list">
    <button class="new_product">
        <a href={% url 'adminapp:product_create' category.pk %}>
        новый продукт
        </a>
    </button>

    {% for object in object_list %}
    <div class="product_record
        {% if not object.is_active %}
            not_active
        {% endif %}">
        <img
                src="{{ object.image|media_for_products }}"
                alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href={% url 'adminapp:product_read' object.pk %}>
                подробнее
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:product_update' object.pk %}>
                редактировать
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:product_delete' object.pk %}>
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
                </a>
            </button>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/reports.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<div class="products_list">
    {% for object in object_list %}
    <div class="product_record
        {% if not object.product.is_active %}
            not_active
        {% endif %}">
        <img
                src="{{ object.product.image|media_for_products }}"
                alt="{{ object.product.name }}">
        <div class="product_name">
            {{ object.product.name|title }}
        </div>

        <div class="summary">

            <b>количество покупок</b>
            <p>{{ object.quantity }}</p>
        </div>

    </div>
    {% endfor%}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="user_delete">
    {% if user_to_delete.is_active %}
        Уверены, что хотите удалить
    {% else %}
        Уверены, что хотите восстановить
    {% endif %}

    {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
    ({{ user_to_delete.first_name|title }}
    {% if user_to_delete.last_name %}
    {{ user_to_delete.last_name|title }}
    {% endif %})
    {% endif %}
    ?
    <form action="{% url 'adminapp:user_delete' user_to_delete.pk %}"
          method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="уверен">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'adminapp:user_list' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:user_list' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<div class="users_list">
    <button class="new_user">
        <a href={% url 'adminapp:user_create' %}>
        новый пользователь
        </a>
    </button>
    {% for object in object_list %}
    <div
            class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img
                src="{{ object.avatar|media_for_users }}"
                alt="{{ object.username }}">
        <div class="user_role">
            {% if object.is_superuser %}
            администратор
            {% else %}
            пользователь
            {% endif %}
            <button>
                <a href={% url 'adminapp:user_update' object.pk %}>
                редактировать
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:user_delete' object.pk %}>
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
                </a>
            </button>
        </div>
        <div class="user_name">
            <p><strong>{{ object.username }}</strong></p>
            <p>
                {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
            <p>{{ object.last_name|title }}</p>
            {% endif %}
            {% endif %}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ object.age }} лет
        </div>
        <div class="user_email">
            email:<br>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}