geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
    path('favourite/', authapp.FavouriteListView.as_view(), name='favourite'),
    path('favourite/delete/<int:pk>/', authapp.FavouriteDeleteView.as_view(), name='favourite_delete'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp


urlpatterns = [
    path('', mainapp.main, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('order/', include('ordersapp.urls', namespace='order')),

    # path('admin/', admin.site.urls, name='admin'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.ProductsListView.as_view(), name='category'),
    # path('category/<int:pk>/ajax/', mainapp.products_ajax),
    # path('category/<int:pk>/page/<int:page>/ajax/', mainapp.products_ajax),
    # path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('product/ajax/<int:pk>/', mainapp.add_to_favourite, name='favourite_add'),
    path('api/load/', mainapp.product_upload),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id',)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='изображение')
    short_desc = models.CharField(max_length=255, verbose_name='краткое описание')
    description = models.TextField(verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество на складе')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class ExchangeRate(models.Model):
    rate = models.DecimalField(decimal_places=2, max_digits=5, default=0, verbose_name='курс валюты')
    rate_update_at = models.DateField(auto_now=True, verbose_name='обновлен')

geekshop/mainapp/views.py
import json
import os
import random
from datetime import date
from urllib import request
from xml.dom import minidom

from django.conf import settings
from django.core.cache import cache
from django.http import JsonResponse, Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from authapp.models import ShopUserFavourite
from mainapp.models import Product, ProductCategory, ExchangeRate
from basketapp.models import Basket


def get_exchange_rate():
    rate = ExchangeRate.objects.filter(rate_update_at=date.today()).first()

    if not rate:
        url = 'http://www.cbr.ru/scripts/XML_daily.asp'
        web_xml = request.urlopen(url)
        xml_data = web_xml.read()

        filename = os.path.join(settings.BASE_DIR, 'tmp') + '/exchange.xml'
        with open(filename, 'wb') as local_xml:
            local_xml.write(xml_data)
            local_xml.close()

        xml = minidom.parse(filename)
        currency = xml.getElementsByTagName('Valute')
        for element in currency:
            charcode = element.getElementsByTagName('CharCode')[0].firstChild.data
            if charcode == 'USD':
                value = float(element.getElementsByTagName('Value')[0].firstChild.data.replace(',', '.'))
                rate = ExchangeRate(rate=value)
                rate.save()
                break

    return rate


def get_usd():
    if settings.LOW_CACHE:
        key = 'usd_exchange'
        usd_exchange = cache.get(key)
        if usd_exchange is None:
            usd_exchange = get_exchange_rate().rate
            cache.set(key, usd_exchange)
        return usd_exchange
    else:
        return get_exchange_rate().rate


def get_price_usd(product_price):
    return product_price / get_usd()


def get_favourite(user, pk):
    return ShopUserFavourite.objects.filter(user=user, product__pk=pk).first()


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        _product = cache.get(key)
        if _product is None:
            _product = get_object_or_404(Product, pk=pk)
            cache.set(key, _product)
        return _product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).\
                select_related().order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).\
                select_related().order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).\
                select_related().order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).\
                select_related().order_by('price')


def get_hot_product():
    try:
        _hot_product = random.sample(list(get_products()), 1)[0]
    except ValueError:
        raise Http404('Отсутствуют продукты в базе данных')
    return _hot_product


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk).\
                        select_related()[:3]
    return same_products


def main(request):

    context = {
        'title': 'Главная',
        'products': get_products()[:4],
        'exchange_rate': get_usd()
    }
    return render(request, 'mainapp/index.html', context=context)


class ProductsListView(ListView):
    template_name = 'mainapp/products_list.html'
    model = Product
    paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk')

        if category_pk != 0:
            queryset = queryset.filter(category__pk=category_pk)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_pk = self.kwargs.get('pk')

        if category_pk == 0:
            context_data['category'] = {
                'name': 'все',
                'pk': 0
            }
        else:
            context_data['category'] = get_category(category_pk)

        context_data['links_menu'] = get_links_menu()
        context_data['title'] = 'Продукты'
        context_data['exchange_rate'] = get_usd()

        return context_data


def products_ajax(request, pk=None, page=1):
    print('controller ajax1')
    if request.is_ajax():
        print('controller ajax')
        links_menu = get_links_menu()
        if pk is not None:
            print(f'pk={pk}')
            if pk == 0:
                products_list = get_products_ordered_by_price()
                category = {
                    'name': 'все',
                    'pk': 0
                }
            else:
                category = get_category(pk)
                products_list = get_products_in_category_ordered_by_price(pk)

            paginator = Paginator(products_list, 2)
            print(products_list)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)
            context = {
                'products': products_paginator,
                'category': category,
                'links_menu': links_menu,
            }
            print(f'paginator: {products_paginator}')
            print(f'object_list: {products_paginator.object_list}')
            result = render_to_string('mainapp/includes/inc_products_list_content.html',
                                      context=context,
                                      request=request)
            print(result)
            return JsonResponse({'result': result})


def products(request, pk=None, page=1):
    title = 'Продукты'
    links_menu = get_links_menu()
    # print('controller products')
    # if pk is not None:
    #     if pk == 0:
    #         products_list = get_products_ordered_by_price()
    #         category = {
    #             'name': 'все',
    #             'pk': 0
    #         }
    #     else:
    #         category = get_object_or_404(ProductCategory, pk=pk)
    #         products_list = get_products_in_category_ordered_by_price(pk)
    #
    #     paginator = Paginator(products_list, 2)
    #     print(products_list)
    #     try:
    #         products_paginator = paginator.page(page)
    #     except PageNotAnInteger:
    #         products_paginator = paginator.page(1)
    #     except EmptyPage:
    #         products_paginator = paginator.page(paginator.num_pages)
    #     context = {
    #         'products': products_paginator,
    #         'category': category,
    #         'links_menu': links_menu,
    #         'title': title,
    #     }
    #
    #     return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'links_menu': links_menu,
        'title': title,
        'hot_product': hot_product,
        'same_products': same_products,
        'exchange_rate': get_usd(),
        'price_usd': get_price_usd(hot_product.price),
    }

    return render(request, 'mainapp/products.html', context=context)


def contact(request):
    context = {
        'title': 'Контакты',
        'exchange_rate': get_usd(),
    }
    return render(request, 'mainapp/contact.html', context=context)


def product(request, pk):
    title = 'продукты'
    _product = get_product(pk)
    context = {
        'title': title,
        'links_menu': get_links_menu(),
        'product': _product,
        'favourite': get_favourite(request.user, pk),
        'exchange_rate': get_usd(),
        'price_usd': get_price_usd(_product.price)
    }

    return render(request, 'mainapp/product.html', context)


def add_to_favourite(request, pk):

geekshop/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="interkassa-verification" content="3b4c7336a405f8f03e2420c89f993564" />
	<title>{% block title %}{{ title|capfirst }}{% endblock %}</title>
	{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
	{% endblock %}

	{% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--    <script src="{% static 'js/favourite.js' %}"></script>-->
<!--    <script src="{% static 'js/main_script.js' %}"></script>-->
	{% endblock %}
</head>
<body>
	<div class="container">
		{% block menu %}
		{% endblock %}

		{% block content %}
		{% endblock %}

		<div class="clr"></div>

	</div>

	{% block footer %}
	<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
	{% endblock %}

</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block menu %}
<div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <h1>наши контакты</h1>
</div>
{% endblock %}

{% block content %}
<div class="location">
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}
<div class="slider">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{% url 'products:product' product.pk %}"><img src="{{ product.image|media_for_products }}" alt="">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }} </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}

<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="{{ product.image|media_for_products }}"
                     alt="{{ product.short_desc }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#">
                        <img src="{{ product.image|media_for_products }}" alt="вариант 1">
                    </a>
                </div>
                <div class="block">
                    <a href="#">
                        <img src="{{ product.image|media_for_products }}" alt="вариант 2">
                    </a>
                </div>
                <div class="block">
                    <a href="#">
                        <img src="{{ product.image|media_for_products }}" alt="вариант 3">
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <br>
            <p class="price"> {{ product.price }} <span>руб</span></p>
            <p class="price"> {{ price_usd|floatformat:2 }} <span>USD</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            {% include 'mainapp/includes/inc_favourite_button.html' %}

            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>

</div>

<div class="clr"></div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="{{ hot_product.image|media_for_products }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{{ hot_product.image|media_for_products }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{{ hot_product.image|media_for_products }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{{ hot_product.image|media_for_products }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.name|capfirst }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{hot_product.price|floatformat:2}} <span>руб</span></p>
            <p class="price"> {{price_usd|floatformat:2}} <span>USD</span></p>
            <a href="{% url 'products:product' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{ hot_product.short_desc }}</p>
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product in same_products %}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}"><img src="{{ product.image|media_for_products }}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.category.name }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}

<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    {% include 'mainapp/includes/inc_products_list_content.html' %}
</div>

<div class="clr"></div>

{% endblock %}